[project]
name = "countdown"
version = "0.1.0"
description = "A count down app in terminal."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "platformdirs>=4.3.8",
    "textual>=3.2.0",
]
